// Country names in Spanish for WorldMap tooltips
export const countryNamesES: Record<string, string> = {
  'us': 'Estados Unidos',
  'ar': 'Argentina',
  'br': 'Brasil',
  'mx': 'México',
  'es': 'España',
  'co': 'Colombia',
  'cl': 'Chile',
  'pe': 'Perú',
  'uy': 'Uruguay',
  've': 'Venezuela',
  'ec': 'Ecuador',
  'py': 'Paraguay',
  'bo': 'Bolivia',
  'pa': 'Panamá',
  'cr': 'Costa Rica',
  'gt': 'Guatemala',
  'hn': 'Honduras',
  'sv': 'El Salvador',
  'ni': 'Nicaragua',
  'cu': 'Cuba',
  'do': 'República Dominicana',
  'pr': 'Puerto Rico',
  'ca': 'Canadá',
  'gb': 'Reino Unido',
  'uk': 'Reino Unido',
  'fr': 'Francia',
  'de': 'Alemania',
  'it': 'Italia',
  'pt': 'Portugal',
  'nl': 'Países Bajos',
  'be': 'Bélgica',
  'ch': 'Suiza',
  'at': 'Austria',
  'se': 'Suecia',
  'no': 'Noruega',
  'dk': 'Dinamarca',
  'fi': 'Finlandia',
  'pl': 'Polonia',
  'ru': 'Rusia',
  'ua': 'Ucrania',
  'tr': 'Turquía',
  'gr': 'Grecia',
  'cn': 'China',
  'jp': 'Japón',
  'kr': 'Corea del Sur',
  'in': 'India',
  'au': 'Australia',
  'nz': 'Nueva Zelanda',
  'za': 'Sudáfrica',
  'eg': 'Egipto',
  'ng': 'Nigeria',
  'ke': 'Kenia',
  'ma': 'Marruecos',
  'dz': 'Argelia',
  'tn': 'Túnez',
  'ae': 'Emiratos Árabes Unidos',
  'sa': 'Arabia Saudita',
  'il': 'Israel',
  'iq': 'Irak',
  'ir': 'Irán',
  'pk': 'Pakistán',
  'bd': 'Bangladesh',
  'th': 'Tailandia',
  'vn': 'Vietnam',
  'id': 'Indonesia',
  'my': 'Malasia',
  'ph': 'Filipinas',
  'sg': 'Singapur',
};
